config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root to: 'pages#landing'

  get 'review/:student_id', to: 'pages#review', as: 'review'

  get 'review/:student_id/self', to: 'pages#self', as: 'review_self'
  post 'review/:student_id/self_submit', to: 'pages#self_submit', as: 'review_self_submit'

  get 'review/:student_id/team', to: 'pages#team', as: 'review_team'
  post 'review/:student_id/team_submit/:id', to: 'pages#team_submit', as: 'review_team_submit'

  get 'passcode/:student_id', to: 'students#passcode', as: 'passcode'
  post 'passcode/:student_id/submit', to: 'students#passcode_submit', as: 'passcode_submit'

  namespace :admin do
    get 'manage', to: 'pages#manage', as: 'manage'
    get 'export', to: 'pages#export', as: 'export'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable, :recoverable,
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord

  belongs_to :reviewer, class_name: 'Student', foreign_key: :reviewer_id
  belongs_to :reviewee, class_name: 'Student', foreign_key: :reviewee_id

  validates :answer1, presence: true
  validates :answer2, presence: true

end

app/models/self_reflection.rb
class SelfReflection < ApplicationRecord

  belongs_to :student

  validates :answer1, presence: true
  validates :answer2, presence: true

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :self_reflections

  has_many :feedback_as_reviewer, class_name: 'Feedback', foreign_key: :reviewer_id
  has_many :feedback_as_reviewee, class_name: 'Feedback', foreign_key: :reviewee_id

  has_many :teams_as_student, class_name: 'Team', foreign_key: :student_id
  has_many :teams_as_teammate, class_name: 'Team', foreign_key: :teammate_id
  has_many :teammates, through: :teams_as_student, source: :teammate

  validates :name, presence: true
  validates :passcode, presence: true

  def self.retrieve_relevant_records(current_student=nil)
    where.not(name: 'z.test', id: current_student&.id).order(name: :asc)
  end

end

app/models/team.rb
class Team < ApplicationRecord

  belongs_to :student
  belongs_to :teammate, class_name: 'Student', foreign_key: :teammate_id

  def self.permutate_team_into_pairs(groups)
    groups.map { |group| group.permutation(2).to_a }.flatten(1)
  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController

  before_action :authenticate_admin!

  def manage
    @students = Student.retrieve_relevant_records
    @feedback = Feedback.all
  end

  def export
    @students = Student.retrieve_relevant_records
    @feedback = Feedback.all

    respond_to do |format|
      format.xls
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def verify_passcode
    @student = Student.find(params[:student_id])
    authentication = AuthenticationService.new(@student)
    unless authentication.session_verify(session)
      redirect_to passcode_path(student_id: @student)
    end
  end

  def after_sign_in_path_for(resource)
    if resource.class.name == 'Admin'
      admin_manage_path
    else
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :verify_passcode, except: [:landing]

  def landing
    @students = Student.order(name: :asc)
  end

  def review
    @student = Student.find(params[:student_id])
    @students = Student.retrieve_relevant_records(@student)
  end

  def self
    @student = Student.find(params[:student_id])
    @self_reflection = SelfReflection.new
  end

  def self_submit
    @student = Student.find(params[:student_id])

    self_reflection_params = params.require(:self_reflection).permit(:answer1, :answer2)
    @self_reflection = @student.self_reflections.build(self_reflection_params)
    if @self_reflection.save
      redirect_to review_path(student_id: @student)
    else
      render :self
    end
  end

  def team
    @student = Student.find(params[:student_id])
    @feedback = Feedback.new
    @teammate = Student.find(params[:id])
  end

  def team_submit
    @student = Student.find(params[:student_id])
    @teammate = Student.find(params[:id])

    feedback_params = params.require(:feedback).permit(:answer1, :answer2)
    @feedback = @student.feedback_as_reviewer.build(feedback_params)
    @feedback.reviewee = @teammate
    if @feedback.save
      redirect_to review_path(student_id: @student)
    else
      render :team
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def passcode
    @student = Student.find(params[:student_id])
  end

  def passcode_submit
    @student = Student.find(params[:student_id])
    received_passcode = params[:passcode]
    authentication = AuthenticationService.new(@student, received_passcode)
    if authentication.passcode_verify
      authentication.record(session)
      redirect_to review_path(student_id: @student)
    else
      flash[:alert] = 'Authentication failed! Check that you have entered the right passcode (given to you on Slack by Sarine)'
      render :passcode
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def welcome_message
    @student ? "Welcome, #{@student.name}!" : 'Welcome!'
  end

  def pending_teammate_feedback?(student)
    student.teammates.count > student.feedback_as_reviewer.where(reviewee: student.teammates).count
  end

end

app/views/admin/pages/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Self Reflections">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Student</Data></Cell>
        <Cell><Data ss:Type="String">Self-reflection</Data></Cell>
        <Cell><Data ss:Type="String">Reflect on the 3 team projects you've done so far. What have you learned about yourself and how you work in teams? What worked and what didn't?</Data></Cell>
        <Cell><Data ss:Type="String">How would you apply your observations from Q1 in your capstone project? What would you do differently?</Data></Cell>
      </Row>

      <% @students.each do |student| %>
        <Row>
          <Cell><Data ss:Type="String"><%= student.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= student.self_reflections.count %></Data></Cell>
          <% unless student.self_reflections.empty? %>
            <Cell><Data ss:Type="String"><%= student.self_reflections.first.answer1 %></Data></Cell>
            <Cell><Data ss:Type="String"><%= student.self_reflections.first.answer2 %></Data></Cell>
          <% end %>
        </Row>
      <% end %>
    </Table>
  </Worksheet>

  <Worksheet ss:Name="Teammate Feedback">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Reviewer</Data></Cell>
        <Cell><Data ss:Type="String">Reviewee</Data></Cell>
        <Cell><Data ss:Type="String">What are you grateful to this teammate for? Feel free to talk about your observations of this person or how they have positively affected you. You may also share anything you have learned from this teammate.</Data></Cell>
        <Cell><Data ss:Type="String">Do you have any constructive feedback for this teammate? Feel free to offer words of encouragement as well!</Data></Cell>
      </Row>

      <% @feedback.each do |feedback| %>
        <Row>
          <Cell><Data ss:Type="String"><%= feedback.reviewer.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= feedback.reviewee.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= feedback.answer1 %></Data></Cell>
          <Cell><Data ss:Type="String"><%= feedback.answer2 %></Data></Cell>
        </Row>
      <% end %>
    </Table>
  </Worksheet>

</Workbook>

app/views/admin/pages/manage.html.slim
.container-fluid
  .row
    .col-md-10.col-md-offset-1
      ul.nav.nav-tabs
        li.active
          a href='#overview' data-toggle='tab' Overview
        li
          a href='#self' data-toggle='tab' Self-reflections
        li
          a href='#team' data-toggle='tab' Teammate feedback

      .tab-content.clearfix
        .tab-pane.active#overview
          .col-md-8.col-md-offset-2

            h1 Overview

            table.table.table-hover.table-striped.table-bordered
              thead
                tr
                  th Student
                  th.text-center Self-reflection?
                  th.text-center Teammate feedback #
              tbody
                - @students.each do |student|
                  tr
                    td = student.name
                    td.text-center
                      - if student.self_reflections.empty?
                        span.label.label-danger<> Pending
                      - else
                        span.label.label-success<> Completed
                    td.text-center class=(pending_teammate_feedback?(student) ? 'pending' : 'completed') = student.feedback_as_reviewer.count

        .tab-pane#self
          h1 Self-reflections

          table.table.table-hover.table-striped
            thead
              tr
                th Student
                th Reflect on the 3 team projects you've done so far. What have you learned about yourself and how you work in teams? What worked and what didn't?
                th How would you apply your observations from Q1 in your capstone project? What would you do differently?
            tbody
              - @students.each do |student|
                tr
                  td = student.name
                  - unless student.self_reflections.empty?
                    td = student.self_reflections.first.answer2
                    td = student.self_reflections.first.answer1
                  - else
                    td
                    td

        .tab-pane#team
          h1 Teammate feedback

          table.table.table-hover.table-striped
            thead
              tr
                th Reviewer
                th Reviewee
                th What are you grateful to this teammate for? Feel free to talk about your observations of this person or how they have positively affected you. You may also share anything you have learned from this teammate.
                th Do you have any constructive feedback for this teammate? Feel free to offer words of encouragement as well!
            tbody
              - @feedback.each do |feedback|
                tr
                  td = feedback.reviewer.name
                  td = feedback.reviewee.name
                  td = feedback.answer1
                  td = feedback.answer2

      .text-center
        = link_to 'Export all data to .xls', admin_export_path(format: 'xls'), class: 'btn btn-default'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse
  .container-fluid.nav-container

    = link_to url_for(:back), class: 'navbar-text' do
      span.glyphicon.glyphicon-chevron-left<>
      | Back

    - if admin_signed_in?
      = link_to 'View submissions', admin_manage_path, class: 'navbar-text'
      = link_to 'Admin sign out', destroy_admin_session_path, class: 'navbar-text'

    = link_to root_path, class: 'navbar-text home text-center' do
      span.glyphicon.glyphicon-home<>
      | Home


    p.navbar-text.pull-right
      strong #{welcome_message}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamworkReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <%= yield %>

  </body>
</html>

app/views/pages/_checklist.html.slim
.col-md-2.col-md-offset-1#checklist.mobile-hide

  h1 Checklist

  ul
    - if @student.self_reflections.empty?
      li.pending
        i.fa.fa-square-o<>
        | Complete self-reflection
    - else
      li.completed
        i.fa.fa-check-square-o<>
        | Complete self-reflection

    - if pending_teammate_feedback?(@student)
      li.pending
        i.fa.fa-square-o<>
        | Provide feedback on shopping cart teammates
    - else
      li.completed
        i.fa.fa-check-square-o<>
        | Provide feedback on shopping cart teammates

    li.pending
      i.fa.fa-square-o<>
      span
        | (optional)
      |  Provide feedback on previous teammates

app/views/pages/_self_feedback.html.slim
h1 Part A: Self-Reflection

.well
  - if @student.self_reflections.empty?
    = link_to 'Answer the questions on self-reflection', review_self_path(student_id: @student)
    span.label.label-danger<> Pending
  - else
    | Answer the questions on self-reflection
    span.label.label-success<> Completed

app/views/pages/_team_feedback.html.slim
h1 Part B: Teammate Feedback
p You've spent 5 weeks working in teams. Have you learned more about your teammates? Feel free to leave feedback for anyone you have previously worked with as well!
hr

.well
  strong Is there anything your teammate did that inspired you? Is there any advice you would offer them? Or do you just want to thank them for putting in extra effort? Take this chance to do it!

hr
small
  em Try to provide constructive feedback and expound on your points as much as possible. Feedback shared with your teammates will be aggregated.

table.table.table-hover.table-striped
  thead
    tr
      th
      th
  tbody
    - @students.each do |student|
      tr
        td
          - if Team.exists?(student: @student, teammate: student) && !Feedback.exists?(reviewer: @student, reviewee: student)
            span.label.label-danger<> Pending
          - if Feedback.exists?(reviewer: @student, reviewee: student)
            span.label.label-success<> Completed
        td.pull-left
          = link_to student.name, review_team_path(student_id: @student, id: student)

app/views/pages/landing.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-4.text-center

      h1 Teamwork: Self-Reflections and Teammate Feedback (Week 9)

      .well You have now completed your shopping cart app and will be embarking on the final group project of the bootcamp: the capstone. Take some time to reflect on how well you have interacted and worked with your classmates and how you will apply it going forward in your coming capstone project team. You will also have the opportunity to offer words of encouragement to or feedback for your teammates!

      h2 Pick your name to continue

      .well
        - @students.each do |student|
          =<> link_to student.name, review_path(student_id: student), class: 'btn btn-default'

app/views/pages/review.html.slim
.container-fluid

  .row
    = render 'checklist'

    .col-md-4.col-md-offset-1.text-center

      = render 'self_feedback'

      = render 'team_feedback'

app/views/pages/self.html.slim
.container-fluid
  .row
    .col-md-6.col-md-offset-3

      h1 Self-Reflection

      = simple_form_for @self_reflection, url: review_self_submit_path(student_id: @student), method: :post do |f|

        p 1. Reflect on the 3 team projects you've done so far. What have you learned about yourself and how you work in teams? What worked and what didn't?
        = f.input :answer1, label: false, error: 'Answers are mandatory, please fill in the form fully.'

        p 2. How would you apply your observations from Q1 in your capstone project? What would you do differently?
        = f.input :answer2, label: false, error: 'Answers are mandatory, please fill in the form fully.'

        .text-center
          = f.submit 'Submit reflection', class: 'btn btn-default'

app/views/pages/team.html.slim
.container-fluid
  .row
    .col-md-6.col-md-offset-3

      h1 Teammate Feedback: #{@teammate.name}

      = simple_form_for @feedback, url: review_team_submit_path(student_id: @student, id: @teammate), method: :post do |f|

        p What are you grateful to this teammate for? Feel free to talk about your observations of this person or how they have positively affected you. You may also share anything you have learned from this teammate.
        = f.input :answer1, label: false, error: 'Answers are mandatory, please fill in the form fully.'

        p Do you have any constructive feedback for this teammate? Feel free to offer words of encouragement as well!
        = f.input :answer2, label: false, error: 'Answers are mandatory, please fill in the form fully.'

        .text-center
          = f.submit 'Submit feedback', class: 'btn btn-default'

app/views/students/passcode.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-4

      h1 Enter your passcode to continue

      = form_tag passcode_submit_path(student_id: @student), method: :post do
        .input-group
            = password_field_tag :passcode, nil, class: 'form-control', required: true, autofocus: true
            span.input-group-btn
              = submit_tag 'Submit', class: 'btn btn-default'

      - if flash.alert
        .alert.alert-danger
          p = flash.alert